### ISSUE TITLE
No answer to "help" command

### ISSUE THREAD

**Issue by cyberdie** [SenTzu01/pimatic-telegram#42] opened 2018-06-04 17:30 UTC
Plugin works ok for other commands but help command is never answered.
Password is accepted without problems.

pimatic-daemon.log shows the following:
`can't parse entities: Unsupported start tag "device" at byte offset 50`
Perhaps some problem parsing the response?

**Comment by cyberdie** [comment] 2018-07-11 07:08
Still with this issue under last Pimatic version

Complete error:

`error [pimatic-telegram]: [Message] Sending Telegram "Default commands:
	help
	list devices
	get device <device name | device id>

Rule commands: 

Any command following rule action syntax
Examples:
	'turn on <device>'
	'set temp of <device> to 21'
" to XXXXXX: failed; reason: Bad Request: can't parse entities: Unsupported start tag "device" at byte offset 50`

**Comment by manonfgoo** [comment] 2019-06-07 01:06
have the same issue

**Comment by SenTzu01** [comment] 2019-11-03 11:14
Duplicate of #43

**Closed by SenTzu01** 2019-11-03 11:14 UTC
