### ISSUE TITLE
Unexpected token error on startup

### ISSUE THREAD

**Issue by MMore** [SenTzu01/pimatic-telegram#4] opened 2017-01-07 12:50 UTC
I installed v1.1.0 of your plugin for the first time. In my opinion everything is correctly configured. But I get an error on startup:

13:44:36.140 [pimatic] info: Starting pimatic version 0.9.37
13:44:51.900 [pimatic, ppm] info: 2.15.11
13:44:52.200 [pimatic] info: Loading plugin: "pimatic-cron" (0.8.8)
13:44:55.984 [pimatic] info: Loading plugin: "pimatic-hap" (0.9.2)
13:44:59.748 [pimatic] info: Loading plugin: "pimatic-mobile-frontend" (0.9.11)
13:45:04.137 [pimatic] info: Loading plugin: "pimatic-ping" (0.9.5)
13:45:04.449 [pimatic] info: Loading plugin: "pimatic-coc" (0.9.0)
13:45:06.271 [pimatic] info: Loading plugin: "pimatic-shell-execute" (0.9.7)
13:45:06.508 [pimatic] info: Loading plugin: "pimatic-sysinfo" (0.9.4)
13:45:07.590 [pimatic] info: Loading plugin: "pimatic-sunrise" (0.8.7)
13:45:07.816 [pimatic] info: Loading plugin: "pimatic-pushsafer" (1.0.3)
13:45:08.053 [pimatic] info: Loading plugin: "pimatic-sms" (1.0.3)
13:45:13.343 [pimatic] info: Loading plugin: "pimatic-z-way" (1.4.2)
13:45:13.596 [pimatic] info: Loading plugin: "pimatic-telegram" (1.1.0)
13:45:13.819 [pimatic] error: Unexpected token {
13:45:14.899 [pimatic] debug: SyntaxError: Unexpected token {
13:45:14.899 [pimatic] debug:>    at exports.runInThisContext (vm.js:53:16)
13:45:14.899 [pimatic] debug:>    at Module._compile (module.js:373:25)
13:45:14.899 [pimatic] debug:>    at Object.Module._extensions..js (module.js:416:10)
13:45:14.899 [pimatic] debug:>    at Module.load (/opt/pimatic-app/node_modules/pimatic-mo
bile-frontend/node_modules/nap/node_modules/coffee-script/lib/coffee-script/register.js:45
:36)
13:45:14.899 [pimatic] debug:>    at Function.Module._load (module.js:300:12)
13:45:14.899 [pimatic] debug:>    at Module.require (module.js:353:17)
13:45:14.899 [pimatic] debug:>    at require (internal/module.js:12:17)
**13:45:14.899 [pimatic] debug:>    at module.exports (/opt/pimatic-app/node_modules/pimatic
-telegram/telegram.coffee:6:23)**
13:45:14.899 [pimatic] debug:>    at PluginManager.loadPlugin (/opt/pimatic-app/node_modul
es/pimatic/lib/plugins.coffee:83:16)
13:45:14.899 [pimatic] debug:>    at /opt/pimatic-app/node_modules/pimatic/lib/plugins.cof
fee:477:25
13:45:14.899 [pimatic] debug:>    at tryCatcher (/opt/pimatic-app/node_modules/pimatic/nod
e_modules/bluebird/js/release/util.js:16:23)
13:45:14.899 [pimatic] debug:>    at Promise._settlePromiseFromHandler (/opt/pimatic-app/n
ode_modules/pimatic/node_modules/bluebird/js/release/promise.js:510:31)
13:45:14.899 [pimatic] debug:>    at Promise._settlePromise (/opt/pimatic-app/node_modules
/pimatic/node_modules/bluebird/js/release/promise.js:567:18)
13:45:14.899 [pimatic] debug:>    at Promise._settlePromiseCtx (/opt/pimatic-app/node_modu
les/pimatic/node_modules/bluebird/js/release/promise.js:604:10)
13:45:14.899 [pimatic] debug:>    at Async._drainQueue (/opt/pimatic-app/node_modules/pima
tic/node_modules/bluebird/js/release/async.js:143:12)
13:45:14.899 [pimatic] debug:>    at Async._drainQueues (/opt/pimatic-app/node_modules/pim
atic/node_modules/bluebird/js/release/async.js:148:10)
13:45:14.899 [pimatic] debug:>    at Immediate.Async.drainQueues [as _onImmediate] (/opt/p
imatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:17:14)
13:45:14.899 [pimatic] debug:>    at processImmediate [as _immediateCallback] (timers.js:3
83:17)

Can you help?

**Comment by mwittig** [comment] 2017-01-07 14:12
@MMore See https://forum.pimatic.org/topic/2624/receives-messages-telegram/18

**Comment by SenTzu01** [comment] 2017-01-08 21:01
@MMore Thanks for reporting. Issue was caused by dependencies relying on node V6. This has been fixed now (release 1.1.1).

**Closed by SenTzu01** 2017-01-08 21:01 UTC
