### ISSUE TITLE
Telegram receiver rules are not applied for recreated telegram receiver device

### ISSUE THREAD

**Issue by MMore** [SenTzu01/pimatic-telegram#13] opened 2017-01-15 16:32 UTC
As I wrote in #12 I needed to recreate the telegram receiver device to establish a connection to the Telegram API.

So I noticed that my already defined rules that use the `when telegram received` predicate are not applied properly. When I am entering `help` in Telegram those rule commands are not shown. After saving the belonging rules again, those rule commands are visible and can be triggered.

**Comment by SenTzu01** [comment] 2017-01-15 23:02
Did this happen one-off after recreating the device? In that case this seems to be as designed within the Pimatic core, as the rules were already present and parsed, and will not be parsed again on creation of a Pimatic device.

**Comment by SenTzu01** [comment] 2017-01-16 09:06
Bug confirmed. Getting index of commands array did not work properly, and has been fixed in dev. Will be included in the next release

**Comment by SenTzu01** [comment] 2017-01-16 20:27
Two distinct issues: one has been fixed in 1.1.13, but the main issue remains: Workaround is to restart pimatic after recreating (changing settings) on your receiver device. Need to identify a way to reparse relevant rules upon recreation of device. Fix planned for 1.1.14

**Comment by SenTzu01** [comment] 2017-01-19 09:16
Rules will be reloaded on device reload. Fixed on dev branch, and will be included in next release.

**Closed by SenTzu01** 2017-01-19 09:16 UTC
Labels: bug
