### ISSUE TITLE
Socket error on startup when using telegram receiver

### ISSUE THREAD

**Issue by MMore** [SenTzu01/pimatic-telegram#12] opened 2017-01-15 16:28 UTC
Hi,

I just tested out your new version. On startup I see the following error in log:

    [bot.error.webhook] { [Error: socket hang up] code: 'ECONNRESET' }

Sending a message via telegram does not work until I update the telegram receiver device (which leads to recreation and a properly bot start). After this I can control my home using telegram messages.

And idea? I am using the default device configuration.

**Comment by SenTzu01** [comment] 2017-01-15 23:30
Was this a one-off event? 
Have you upgraded from a previous version and what version are you on currently? 
Did you install via Pimatic and npmjs or did you clone my github repository?
**Do you deploy a firewall or any intermediary software / hardware devices that may filter traffic between the Pimatic host and the telegram API server?**

The error seems to indicate that the remote end (In this case the Telegram API server did a reset on the connection during startup. This however can also be caused by any intermediary hard/software devices in the connection chain.

This is the first report I have seen on this issue, so I am interested in understanding how your environment is different from users who now seem to be able to use the plugin without issues.

**Comment by SenTzu01** [comment] 2017-01-15 23:44
Also see https://github.com/request/request/issues/2047. This may be related, but this depends on which version of node.js you run

**Comment by MMore** [comment] 2017-01-17 22:29
See answers below:

Was this a one-off event? _No, have the same issues for all startups so far._
Have you upgraded from a previous version and what version are you on currently? _Yes, I made a downgrade to to v1.0.8 to make basic notifications work. Now I am on v1.1.2._
Did you install via Pimatic and npmjs or did you clone my github repository? _Everything via npm command._
Do you deploy a firewall or any intermediary software / hardware devices that may filter traffic between the Pimatic host and the telegram API server? _No._

**Comment by SenTzu01** [comment] 2017-01-18 10:59
You could try deleting your pimatic-telegram directory in node_modules, and restart pimatic to ensure any residuals from the downgrade are cleaned. Restarting pimatic should reinstall the latest pimatic-telegram and leave your config in place. If this doesnt work, please contact me offline? (email) and we'll investigate this issue in more detail (ECONNRESET).

**Comment by SenTzu01** [comment] 2017-01-20 00:08
Closing issue as no further info was received. Issue is likely caused by transient network conditions or OS socket implementation.

**Closed by SenTzu01** 2017-01-20 00:08 UTC
Labels: question
